### ISSUE TITLE
When will the upstream 1.37.2 be merged?

### ISSUE THREAD

**Issue by YuXiaoCoder** [aurora-is-near/borealis-engine-lib#134]
https://github.com/near/nearcore/releases/tag/1.37.2

**Comment by raventid** [comment]
@YuXiaoCoder Please check new release https://github.com/aurora-is-near/borealis-engine-lib/releases/tag/0.27.2 and let me know if it works for you!

**Comment by YuXiaoCoder** [comment]
@raventid 
The new version did get released, but what about the docker image not being built and uploaded in time?
https://hub.docker.com/r/nearaurora/srpc2-refiner/tags

**Comment by aleksuss** [comment]
@spilin, could you please release the corresponding docker image?

**Comment by spilin** [comment]
Released
