### ISSUE TITLE
When will the upstream 1.38.0 be merged?

### ISSUE THREAD

**Issue by YuXiaoCoder** [aurora-is-near/borealis-engine-lib#135]
Near: https://github.com/near/nearcore/releases/tag/1.38.0
Also I've noticed that docker images are often not up to date.

**Comment by raventid** [comment]
@YuXiaoCoder Soon! https://github.com/aurora-is-near/borealis-engine-lib/pull/136

We will also upload docker images soon after the release

**Comment by raventid** [comment]
https://hub.docker.com/layers/nearaurora/srpc2-refiner/0.28.0-1.38.0/images/sha256-27614ada2ac9c656361f62b36cdffe614d95ef160882a82659584189999f8645?context=explore
